local M = {}
M.BOARD_COLUMNS = 25
M.BOARD_ROWS = 25
M.BOARD_CENTER_X = math.floor((1 + M.BOARD_COLUMNS)/2)
M.BOARD_CENTER_Y = math.floor((1 + M.BOARD_ROWS)/2)
M.INVENTORY_COLUMNS = 4
M.INVENTORY_ROWS = 4

return M